name: Virtual Dojo Deployment(Hostinger / VPS)

# Controls when the action will run.
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install

      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: srv503843.hstgr.cloud
          username: ${{ secrets.VPS_SSH_USERNAME }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          port: 22
          script: |
            # Crear directorios en el VPS
            mkdir -p /var/www/html/virtual-dojo/frontend /var/www/html/virtual-dojo/backend

            # Copiar el build del frontend al VPS
            rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./frontend/dist/ ${{ secrets.VPS_SSH_USERNAME }}@srv503843.hstgr.cloud:/var/www/html/virtual-dojo/frontend

            # Copiar el backend al VPS
            rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./backend/ ${{ secrets.VPS_SSH_USERNAME }}@srv503843.hstgr.cloud:/var/www/html/virtual-dojo/backend

            # Conectar al VPS y reiniciar el backend
            ssh ${{ secrets.VPS_SSH_USERNAME }}@srv503843.hstgr.cloud << 'EOF'
            cd /var/www/html/virtual-dojo/backend
            npm install --only=prod
            pm2 restart all || pm2 start server.js --name virtual-dojo
            exit
            EOF
